# Generated by Django 4.1.3 on 2023-02-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NavOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوبار')),
                ('link', models.CharField(max_length=100, verbose_name='لینک نوبار')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(null=True, upload_to='', verbose_name='لوگو')),
                ('alt', models.CharField(max_length=100, null=True, verbose_name='توضیحات لوگو')),
                ('favicon', models.FileField(null=True, upload_to='', verbose_name='آیکون')),
                ('alt2', models.CharField(max_length=100, null=True, verbose_name='توضیحات icon')),
                ('telephon', models.CharField(max_length=30, null=True, verbose_name='تلفن')),
                ('footer_text', models.CharField(max_length=300, null=True, verbose_name='متن فوتر')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='ایمیل')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='ادرس')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False, verbose_name='تنظیمات فعال؟')),
            ],
        ),
        migrations.CreateModel(
            name='NavTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوبار')),
                ('link', models.CharField(max_length=100, verbose_name='لینک نوبار')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitesetting.navone')),
            ],
        ),
        migrations.CreateModel(
            name='FooterTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('link', models.CharField(max_length=100, null=True, verbose_name='لینک صفحه')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitesetting.footerone')),
            ],
        ),
    ]
