# Generated by Django 4.1.3 on 2023-02-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='channel_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
