# Generated by Django 4.1.3 on 2023-02-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='channel_name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
