# Generated by Django 4.1.3 on 2023-02-18 07:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='links',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
