# Generated by Django 4.1.3 on 2023-02-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
