# Generated by Django 4.1.3 on 2023-02-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorys',
        ),
    ]
