# Generated by Django 4.1.3 on 2023-02-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_video_created_video_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='monetize',
            field=models.BooleanField(default=True),
        ),
    ]
