# Generated by Django 4.1.3 on 2023-02-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_video_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
    ]
