# Generated by Django 4.1.3 on 2023-02-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
