# Generated by Django 4.1.3 on 2023-02-16 07:25

from django.db import migrations, models
import youtube.models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_video_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=youtube.models.get_upload_path),
        ),
    ]
