# Generated by Django 4.1.3 on 2023-02-16 07:45

from django.db import migrations, models
import youtube.models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0010_video_show_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to=youtube.models.get_upload_path),
        ),
    ]
