# Generated by Django 4.1.3 on 2023-02-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
