# Generated by Django 4.1.3 on 2023-02-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_channel_name'),
        ('youtube', '0013_remove_video_visited_remove_video_like_video_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='dislike',
        ),
        migrations.AddField(
            model_name='video',
            name='dislike',
            field=models.ManyToManyField(related_name='dislike', to='account.profile'),
        ),
    ]
