# Generated by Django 4.1.3 on 2023-02-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0019_remove_comment_avatar_remove_comment_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
