# Generated by Django 4.1.3 on 2023-02-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_profile_first_name_remove_profile_last_name'),
        ('youtube', '0020_remove_comment_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('profile', 'video')},
        ),
    ]
