# Generated by Django 4.1.3 on 2023-02-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0023_alter_comment_profile_alter_comment_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='pin_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_pin_comment',
            field=models.BooleanField(default=False),
        ),
    ]
